language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
licenses:
   - 'android-sdk-license-.+'
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
before_install:
  - chmod +x gradlew

sudo: false
